from __future__ import annotations

"""Whole-page responsive presentation for the Qt desktop workspace.

The inner business UI always keeps a safe logical geometry.  The outer view
uniformly scales that real QWidget tree to the native window.  Resizing is
handled in two stages:

* live drag: update only the outer transform at a coalesced cadence;
* settle: once resizing pauses, commit one aspect-matched logical canvas size.

The live path intentionally avoids QWidget relayout.  This keeps window dragging
smooth even though the embedded workspace contains tables, forms and image views.
"""

import logging
from typing import Callable

from PySide6.QtCore import QEvent, QObject, QTimer, QSize, Qt, Signal
from PySide6.QtGui import QBrush, QPainter, QPalette, QTransform
from PySide6.QtWidgets import (
    QApplication,
    QComboBox,
    QFrame,
    QGraphicsProxyWidget,
    QGraphicsScene,
    QGraphicsView,
    QWidget,
)

from .responsive_layout import CanvasFit, fit_logical_canvas, fit_scale_to_canvas

logger = logging.getLogger(__name__)


class _PopupLifecycleGuard(QObject):
    """Track combo/menu popups before Qt has a chance to dismiss them.

    ``QApplication.activePopupWidget()`` is not reliable for popups generated by
    widgets embedded in ``QGraphicsProxyWidget``: on some Qt/macOS builds the
    combo private container is proxied and never becomes the application's active
    popup.  The previous responsive guard therefore missed exactly the interval
    in which a pending resize/settle transform could close the dropdown.

    This application-level event filter arms *before* ``QComboBox.showPopup()``
    (mouse/key press) and keeps the responsive canvas frozen until the actual
    popup container has hidden.  It deliberately covers every combo in every
    Studio page, not only the transfer-mode selector.
    """

    stateChanged = Signal(bool)

    _OPEN_KEYS = {
        int(Qt.Key.Key_Space), int(Qt.Key.Key_Return), int(Qt.Key.Key_Enter),
        int(Qt.Key.Key_F4),
    }

    def __init__(self, app: QApplication) -> None:
        super().__init__(app)
        self._app = app
        self._active = False
        self._popup_ids: set[int] = set()
        self._probe_timer = QTimer(self); self._probe_timer.setSingleShot(True)
        self._probe_timer.timeout.connect(self._probe_unshown_combo)
        self._release_timer = QTimer(self); self._release_timer.setSingleShot(True)
        self._release_timer.timeout.connect(self._release_if_clear)
        self._watchdog_timer = QTimer(self); self._watchdog_timer.setSingleShot(True)
        self._watchdog_timer.timeout.connect(self._watchdog_popup_state)
        app.installEventFilter(self)

    @property
    def active(self) -> bool:
        return bool(self._active)

    def _set_active(self, active: bool) -> None:
        active = bool(active)
        if active == self._active:
            return
        self._active = active
        if active:
            self._watchdog_timer.start(240)
        else:
            self._watchdog_timer.stop()
        self.stateChanged.emit(active)

    def _arm_combo(self) -> None:
        self._release_timer.stop()
        self._set_active(True)
        # If the press/key did not actually open a popup (for example a disabled
        # combo), release the guard shortly afterwards.  A real popup Show event
        # cancels this probe and owns the guard until Hide.
        self._probe_timer.start(260)

    @staticmethod
    def _looks_like_popup(obj: object) -> bool:
        if not isinstance(obj, QWidget):
            return False
        try:
            if obj.windowType() == Qt.WindowType.Popup:
                return True
            name = obj.metaObject().className()
            return name in {"QComboBoxPrivateContainer", "QMenu"}
        except RuntimeError:
            return False


    def _watchdog_popup_state(self) -> None:
        """Release a guard even if a platform omits the popup Hide event.

        Some QGraphicsProxyWidget backends destroy the private combo container
        without a conventional Hide notification.  Polling only while the guard
        is active prevents a stale popup id from permanently freezing resize.
        """
        if not self._active:
            return
        visible_ids: set[int] = set()
        try:
            for widget in self._app.allWidgets():
                if self._looks_like_popup(widget) and widget.isVisible():
                    visible_ids.add(id(widget))
        except RuntimeError:
            visible_ids = set()
        if self._popup_ids:
            self._popup_ids.intersection_update(visible_ids)
        if not visible_ids and self._app.activePopupWidget() is None:
            self._release_timer.start(90)
            return
        self._watchdog_timer.start(240)

    def _probe_unshown_combo(self) -> None:
        if self._popup_ids:
            return
        popup = self._app.activePopupWidget()
        if popup is not None:
            return
        self._set_active(False)

    def _release_if_clear(self) -> None:
        if self._popup_ids:
            return
        popup = self._app.activePopupWidget()
        if popup is not None:
            return
        self._set_active(False)

    def eventFilter(self, obj, event):  # noqa: N802 - Qt API
        et = event.type()
        if isinstance(obj, QComboBox):
            if et == QEvent.Type.MouseButtonPress:
                self._arm_combo()
            elif et == QEvent.Type.KeyPress:
                try:
                    key = int(event.key())
                    alt_down = key == int(Qt.Key.Key_Down) and bool(event.modifiers() & Qt.KeyboardModifier.AltModifier)
                    if key in self._OPEN_KEYS or alt_down:
                        self._arm_combo()
                except Exception:
                    pass

        oid = id(obj)
        if oid in self._popup_ids or self._looks_like_popup(obj):
            if et in {QEvent.Type.Show, QEvent.Type.ShowToParent}:
                self._probe_timer.stop()
                self._release_timer.stop()
                self._popup_ids.add(oid)
                self._set_active(True)
            elif et in {QEvent.Type.Hide, QEvent.Type.HideToParent, QEvent.Type.Close, QEvent.Type.Destroy}:
                self._popup_ids.discard(oid)
                # Let the combo commit currentIndex/currentText and restore focus
                # before the outer canvas is allowed to transform again.
                self._release_timer.start(90)
        return False


def _application_popup_guard() -> _PopupLifecycleGuard | None:
    """Compatibility hook; no global combo event filter is installed anymore.

    v2.0.72 restores the v2.0.63-style native popup lifecycle by letting
    ``StableComboBox`` open an independent top-level QMenu.  The old application
    event filter is intentionally disabled because it introduced another focus /
    timer lifecycle around every combo press.  ResponsiveCanvasView still checks
    QApplication.activePopupWidget(), which is reliable for the top-level menu.
    """
    return None


# Public helper retained for downstream callers.
def compute_ui_scale(
    width: int,
    height: int,
    *,
    design_width: int = 1480,
    design_height: int = 960,
    maximum: float | None = None,
) -> float:
    return fit_logical_canvas(
        width,
        height,
        minimum_width=design_width,
        minimum_height=design_height,
        maximum_scale=maximum,
    ).scale


class ResponsiveCanvasView(QGraphicsView):
    """Fit one interactive QWidget canvas to every host-window size.

    ``design_size`` is a layout-safety floor.  The logical canvas may grow to
    match the viewport aspect ratio, but it never shrinks below that floor.

    Native resize events can arrive dozens of times per second.  Relaying each
    one into ``content_root.resize()`` would make Qt recompute the complete
    layout tree repeatedly.  Instead, live resize events only update the view
    transform.  A short settling timer commits the final logical geometry once.
    """

    scaleChanged = Signal(float)

    LIVE_FRAME_MS = 28
    SETTLE_MS = 140
    SCALE_EPSILON = 0.0015

    def __init__(
        self,
        content_root: QWidget,
        *,
        design_size: QSize = QSize(1480, 960),
        maximum_scale: float | None = None,
        on_scale: Callable[[float], None] | None = None,
        parent: QWidget | None = None,
    ) -> None:
        super().__init__(parent)
        self.content_root = content_root
        self.design_size = QSize(design_size)
        self.maximum_scale = maximum_scale
        self.on_scale = on_scale
        self.current_scale = 1.0
        self.logical_size = QSize(self.design_size)
        self._last_viewport_size = QSize()

        self._scene = QGraphicsScene(self)
        self._scene.setStickyFocus(True)
        self.setScene(self._scene)
        self._proxy: QGraphicsProxyWidget = self._scene.addWidget(self.content_root)
        self._proxy.setPos(0.0, 0.0)

        self.setObjectName("responsiveCanvas")
        self.setFrameShape(QFrame.Shape.NoFrame)
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setTransformationAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.setInteractive(True)
        self.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.setRenderHints(
            QPainter.RenderHint.TextAntialiasing
            | QPainter.RenderHint.SmoothPixmapTransform
        )
        # FullViewportUpdate forced every child in the embedded QWidget tree to
        # repaint during native resize.  MinimalViewportUpdate lets Qt invalidate
        # only what the transform/viewport actually changes.
        self.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.MinimalViewportUpdate)
        self.setOptimizationFlag(QGraphicsView.OptimizationFlag.DontAdjustForAntialiasing, True)

        self._live_timer = QTimer(self)
        self._live_timer.setSingleShot(True)
        self._live_timer.timeout.connect(self._apply_live_transform)
        self._settle_timer = QTimer(self)
        self._settle_timer.setSingleShot(True)
        self._settle_timer.timeout.connect(self._commit_settled_layout)
        self._resize_pending_during_popup = False
        self._popup_guard = _application_popup_guard()
        if self._popup_guard is not None:
            self._popup_guard.stateChanged.connect(self._on_popup_guard_changed)

        self.scaleChanged.connect(self._notify_scale)
        self._apply_logical_size(self.logical_size)
        self.sync_background()

    @property
    def proxy(self) -> QGraphicsProxyWidget:
        return self._proxy

    def capture(self) -> None:
        """Initial/final synchronous fit used after the window is constructed."""
        self.apply_for_current_size(force=True)
        logger.info(
            "responsive canvas ready safe=%dx%d logical=%dx%d viewport=%dx%d scale=%.4f",
            self.design_size.width(), self.design_size.height(),
            self.logical_size.width(), self.logical_size.height(),
            self.viewport().width(), self.viewport().height(), self.current_scale,
        )

    def schedule(self) -> None:
        """Coalesce native resize events without relaying each one into layouts."""
        if self._popup_active():
            # Never leave a timer armed while a combo/menu popup is open.  Even a
            # timer scheduled *before* showPopup() can fire inside the popup's
            # event loop and make QGraphicsProxyWidget dismiss it.
            self._resize_pending_during_popup = True
            self._live_timer.stop(); self._settle_timer.stop()
            return
        if not self._live_timer.isActive():
            self._live_timer.start(self.LIVE_FRAME_MS)
        # Restart only the settle timer.  It fires once after resize traffic stops.
        self._settle_timer.start(self.SETTLE_MS)

    def _on_popup_guard_changed(self, active: bool) -> None:
        if active:
            self._resize_pending_during_popup = True
            self._live_timer.stop(); self._settle_timer.stop()
            logger.debug("responsive canvas frozen for popup lifecycle")
            return
        pending = self._resize_pending_during_popup
        self._resize_pending_during_popup = False
        if pending:
            # Defer one event-loop turn so QComboBox can finish committing the
            # selection/focus before we fit the outer canvas again.
            QTimer.singleShot(0, self.schedule)

    def fit_for_current_size(self) -> CanvasFit:
        size = self.viewport().size()
        return fit_logical_canvas(
            max(1, size.width() - 2),
            max(1, size.height() - 2),
            minimum_width=self.design_size.width(),
            minimum_height=self.design_size.height(),
            maximum_scale=self.maximum_scale,
        )

    def factor_for_current_size(self) -> float:
        return self.fit_for_current_size().scale

    def _fit_existing_logical_canvas(self) -> float:
        size = self.viewport().size()
        return fit_scale_to_canvas(
            max(1, size.width() - 2),
            max(1, size.height() - 2),
            self.logical_size.width(),
            self.logical_size.height(),
            maximum_scale=self.maximum_scale,
        )

    def _apply_logical_size(self, size: QSize) -> None:
        """Give inner layouts safe-or-larger geometry; never a squeezed canvas."""
        size = QSize(
            max(self.design_size.width(), size.width()),
            max(self.design_size.height(), size.height()),
        )
        if size == self.logical_size and self.content_root.size() == size:
            return
        self.logical_size = QSize(size)
        self.content_root.setMinimumSize(self.logical_size)
        self.content_root.setMaximumSize(self.logical_size)
        self.content_root.resize(self.logical_size)
        self._scene.setSceneRect(0.0, 0.0, float(size.width()), float(size.height()))
        self.content_root.updateGeometry()

    def _set_scale(self, scale: float, *, force: bool = False, notify: bool = True) -> None:
        scale = max(0.001, float(scale))
        if not force and abs(scale - self.current_scale) < self.SCALE_EPSILON:
            return
        self.current_scale = scale
        transform = QTransform()
        transform.scale(scale, scale)
        self.setTransform(transform, False)
        self.centerOn(self._proxy)
        if notify:
            self.scaleChanged.emit(scale)

    def _popup_active(self) -> bool:
        """Return True from combo press until the popup has fully closed."""
        if self._popup_guard is not None and self._popup_guard.active:
            return True
        app = QApplication.instance()
        return bool(app is not None and app.activePopupWidget() is not None)

    def _apply_live_transform(self) -> None:
        """Cheap resize-frame update: transform only, no QWidget relayout."""
        if self._popup_active():
            self._resize_pending_during_popup = True
            logger.debug("responsive live transform deferred while popup is open")
            return
        scale = self._fit_existing_logical_canvas()
        self._set_scale(scale, notify=False)
        logger.debug(
            "responsive live transform scale=%.4f viewport=%dx%d logical=%dx%d",
            scale, self.viewport().width(), self.viewport().height(),
            self.logical_size.width(), self.logical_size.height(),
        )

    def _commit_settled_layout(self) -> None:
        """Commit one aspect-matched canvas after native resizing pauses."""
        if self._popup_active():
            self._resize_pending_during_popup = True
            logger.debug("responsive settled layout deferred while popup is open")
            return
        self.apply_for_current_size(force=False)
        # Report scale to the Settings diagnostics only once per settled resize;
        # updating that label on every live frame is unnecessary work.
        self.scaleChanged.emit(self.current_scale)

    def apply_for_current_size(self, *, force: bool = False) -> None:
        if not force and self._popup_active():
            self._resize_pending_during_popup = True
            return
        fit = self.fit_for_current_size()
        logical = QSize(fit.logical_width, fit.logical_height)
        size_changed = logical != self.logical_size
        scale_changed = abs(fit.scale - self.current_scale) >= self.SCALE_EPSILON
        if not force and not size_changed and not scale_changed:
            return

        if size_changed:
            self._apply_logical_size(logical)
        self._set_scale(fit.scale, force=force or size_changed)
        logger.debug(
            "responsive settled fit scale=%.4f viewport=%dx%d logical=%dx%d safe=%dx%d",
            fit.scale, self.viewport().width(), self.viewport().height(),
            logical.width(), logical.height(), self.design_size.width(), self.design_size.height(),
        )

    def _notify_scale(self, factor: float) -> None:
        if self.on_scale is not None:
            self.on_scale(float(factor))

    def sync_background(self) -> None:
        try:
            color = self.content_root.palette().color(QPalette.ColorRole.Window)
            self.setBackgroundBrush(QBrush(color))
            palette = self.palette()
            palette.setColor(QPalette.ColorRole.Base, color)
            palette.setColor(QPalette.ColorRole.Window, color)
            self.setPalette(palette)
        except RuntimeError:
            return

    def resizeEvent(self, event) -> None:  # noqa: N802 - Qt API
        super().resizeEvent(event)
        current = self.viewport().size()
        # Some platforms emit duplicate resize events with the same viewport.
        # Dropping them avoids needless timers and repaints while dragging.
        if current == self._last_viewport_size:
            return
        self._last_viewport_size = QSize(current)
        self.schedule()

    def showEvent(self, event) -> None:  # noqa: N802 - Qt API
        super().showEvent(event)
        self.schedule()


# Compatibility alias for callers introduced in v2.0.65.
ResponsiveUiScaler = ResponsiveCanvasView

__all__ = ["ResponsiveCanvasView", "ResponsiveUiScaler", "compute_ui_scale"]
